import { StyleSheet } from "react-native";
import {
  colors,
  radius,
  spacing,
  touchTarget,
  typography,
} from "../../shared/theme";

export const inventoryHeroToolbarFills = {
  danger: colors.dangerSoft,
  warning: colors.warningSoft,
  success: colors.successSoft,
  neutral: colors.mutedSurface,
} as const;

export const inventoryScreenStyles = StyleSheet.create({
  filterToolbar: {
    gap: spacing.sm,
    padding: spacing.sm,
    borderRadius: radius.xxl,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  heroBubble: {
    gap: spacing.sm,
  },
  filterCluster: {
    gap: spacing.xs,
  },
  searchToolbar: {
    minHeight: touchTarget.min,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
  },
  toolbarIconButton: {
    minWidth: touchTarget.min,
    minHeight: touchTarget.min,
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: radius.lg,
  },
  moreMenuButton: {
    minWidth: touchTarget.min,
    minHeight: touchTarget.min,
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  filterPairRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
  },
  filterPairRowDense: {
    flexDirection: "column",
    alignItems: "stretch",
  },
  filterControls: {
    flex: 1,
    minWidth: 0,
    minHeight: touchTarget.min,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
  },
  filterControlsDense: {
    flexDirection: "column",
    alignItems: "stretch",
    flexGrow: 0,
  },
  expiryTrafficRow: {
    flex: 1,
    minWidth: 0,
    minHeight: touchTarget.min,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xxs, // 4px between mini lamps in the cluster
    paddingHorizontal: spacing.xs,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  expiryTrafficLamp: {
    flex: 1,
    minWidth: 0,
    minHeight: touchTarget.min,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: spacing.xxs,
    paddingVertical: spacing.xxs,
    borderRadius: radius.md,
  },
  locationFilterTile: {
    flexGrow: 0,
    flexShrink: 0,
    // 128: default "모든 위치" width; stays put when a location is selected.
    width: spacing.xxxl * 2,
    minHeight: touchTarget.min,
    flexDirection: "row",
    alignItems: "center",
    paddingLeft: spacing.sm,
    paddingRight: spacing.xs,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  locationFilterTileDense: {
    width: "100%",
    flexGrow: 1,
    flexShrink: 1,
  },
  locationFilterTileActive: {
    borderColor: colors.primary,
  },
  locationFilterMain: {
    flex: 1,
    minWidth: 0,
    minHeight: touchTarget.min,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
  },
  locationFilterTitle: {
    flex: 1,
    minWidth: 0,
  },
  filterControlPressed: {
    opacity: 0.82,
  },
  locationOptionGrid: {
    gap: spacing.xs,
  },
  locationOption: {
    minHeight: touchTarget.min,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.xs,
    paddingHorizontal: spacing.sm,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.background,
  },
  locationOptionSelected: {
    borderColor: colors.primary,
    backgroundColor: colors.primarySoft,
  },
  locationOptionLabel: {
    flex: 1,
    minWidth: 0,
    fontSize: typography.bodySmall.fontSize,
    lineHeight: typography.bodySmall.lineHeight,
    fontFamily: typography.bodyStrong.fontFamily,
    color: colors.text,
  },
  locationOptionLabelSelected: {
    color: colors.primary,
    fontFamily: typography.bodyStrong.fontFamily,
  },
  locationOptionMeta: {
    minWidth: touchTarget.min,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: spacing.xs,
  },
  locationOptionCount: {
    fontSize: typography.caption.fontSize,
    lineHeight: typography.caption.lineHeight,
    fontFamily: typography.title.fontFamily,
    color: colors.subtext,
  },
  locationSheetFooter: {
    gap: spacing.xs,
  },
  entryMethodActions: {
    gap: spacing.xs,
  },
  searchField: {
    flex: 1,
    minWidth: 0,
    minHeight: touchTarget.min,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xxs,
    paddingLeft: spacing.xs,
    paddingRight: spacing.xxs,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  searchInput: {
    flex: 1,
    minWidth: 0,
    minHeight: touchTarget.min,
    paddingVertical: spacing.xxs,
    fontSize: typography.bodyStrong.fontSize,
    lineHeight: typography.bodyStrong.lineHeight,
    fontFamily: typography.bodyStrong.fontFamily,
    color: colors.text,
  },
  headerActions: {
    flexDirection: "row",
    alignItems: "center",
    flexShrink: 0,
    gap: spacing.xxs,
  },
  headerFilterButton: {
    minHeight: touchTarget.min,
    minWidth: touchTarget.icon,
    paddingHorizontal: spacing.sm,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xxs,
    borderRadius: radius.lg,
  },
  headerFilterButtonPressed: {
    backgroundColor: colors.surfacePressed,
  },
  headerFilterLabel: {
    fontSize: typography.bodySmall.fontSize,
    lineHeight: typography.bodySmall.lineHeight,
    fontFamily: typography.bodyStrong.fontFamily,
    color: colors.primary,
  },
  headerFilterLabelMuted: {
    color: colors.mutedText,
  },
  selectionRow: {
    minHeight: touchTarget.min,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    borderRadius: radius.xxl,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  selectionSummary: {
    flex: 1,
    minWidth: 0,
    justifyContent: "center",
    minHeight: touchTarget.min,
  },
  selectionTitle: {
    fontSize: typography.body.fontSize,
    lineHeight: typography.body.lineHeight,
    fontFamily: typography.title.fontFamily,
    color: colors.text,
  },
  undoSnackbar: {
    minHeight: touchTarget.min,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderRadius: radius.lg,
    backgroundColor: colors.text,
  },
  undoSnackbarStacked: {
    flexDirection: "column",
    alignItems: "stretch",
  },
  undoSnackbarLabel: {
    flex: 1,
    minWidth: 0,
  },
  undoSnackbarAction: {
    minHeight: touchTarget.min,
    justifyContent: "center",
    paddingHorizontal: spacing.xs,
    borderRadius: radius.md,
  },
  undoSnackbarActionPressed: {
    backgroundColor: colors.subtext,
  },
  undoSnackbarActionLabel: {
    color: colors.warningSoft,
  },
  screenContent: {
    flex: 1,
    gap: spacing.none,
    // Bleed fridge scene to Screen edges; list keeps the 24px inset itself.
    paddingHorizontal: spacing.none,
    paddingTop: spacing.none,
    paddingBottom: spacing.none,
  },
  fridgeScene: {
    flex: 1,
    overflow: "hidden",
  },
  fridgeSceneBackground: {
    ...StyleSheet.absoluteFillObject,
  },
  fridgeSceneVeil: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: colors.background,
    opacity: 0.16,
  },
  listFlex: {
    flex: 1,
  },
  listContent: {
    flexGrow: 1,
    paddingHorizontal: spacing.sm,
    paddingTop: spacing.sm,
    paddingBottom: spacing.xxxl + spacing.sm,
    gap: spacing.sm,
  },
  listHeader: {
    gap: spacing.sm,
  },
  urgencySection: {
    borderRadius: radius.xxl,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    overflow: "hidden",
  },
  urgencySectionHeader: {
    minHeight: touchTarget.min,
    paddingLeft: spacing.sm,
    paddingRight: spacing.xs,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
  },
  urgencySectionHeaderExpanded: {
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
  },
  urgencySectionTitle: {
    flex: 1,
    minWidth: 0,
  },
  urgencySectionToggle: {
    minWidth: touchTarget.min,
    minHeight: touchTarget.min,
    paddingHorizontal: spacing.xs,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.xxs,
    borderRadius: radius.lg,
  },
  urgencySectionBody: {
    backgroundColor: colors.surface,
  },
});
