import { StyleSheet } from "react-native";
import {
  colors,
  radius,
  spacing,
  touchTarget,
  typography,
} from "../../shared/theme";
import {
  SCAN_FRAME_SIDE_INSET,
  SCAN_LINE_HEIGHT,
  SCAN_LINE_INSET,
} from "./scanGuide";

export const scannerScreenStyles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: colors.text,
  },
  overlay: {
    flex: 1,
    justifyContent: "space-between",
    paddingHorizontal: spacing.md,
    paddingBottom: spacing.md,
    zIndex: 1,
    elevation: 1,
  },
  topBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: spacing.sm,
  },
  topBarStacked: {
    flexDirection: "column",
    alignItems: "flex-start",
    gap: spacing.xs,
  },
  iconButton: {
    width: touchTarget.min,
    height: touchTarget.min,
    borderRadius: radius.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.cameraControl,
  },
  iconButtonPressed: {
    backgroundColor: colors.cameraControlPressed,
  },
  stepPill: {
    maxWidth: "80%",
    minHeight: touchTarget.min,
    borderRadius: radius.pill,
    paddingHorizontal: spacing.md,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
    backgroundColor: colors.cameraControl,
  },
  stepProgress: {
    flexDirection: "row",
    gap: spacing.xxs,
  },
  stepSegment: {
    width: spacing.sm,
    height: spacing.xxs,
    borderRadius: radius.pill,
    backgroundColor: colors.mutedText,
  },
  stepSegmentActive: {
    backgroundColor: colors.primary,
  },
  stepPillText: {
    flexShrink: 1,
    fontSize: typography.bodySmall.fontSize,
    lineHeight: typography.bodySmall.lineHeight,
    fontFamily: typography.bodyStrong.fontFamily,
    color: colors.surface,
    textShadowColor: colors.cameraControl,
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  guideStage: {
    flex: 1,
    justifyContent: "center",
    minHeight: 0,
  },
  guideStageCompact: {
    paddingVertical: spacing.xxs,
  },
  guideCluster: {
    position: "relative",
    width: "100%",
  },
  guideClusterCompact: {
    gap: spacing.xs,
  },
  guideBubbleWrap: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: "100%",
    marginBottom: spacing.md,
    paddingHorizontal: spacing.xxs,
  },
  guideMessageCompact: {
    alignSelf: "center",
    maxWidth: "92%",
    borderRadius: radius.lg,
    backgroundColor: colors.cameraControl,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
  },
  guideMessageCompactText: {
    textAlign: "center",
  },
  guideArea: {
    paddingHorizontal: SCAN_FRAME_SIDE_INSET - spacing.md,
  },
  scanFrame: {
    borderRadius: radius.xxl,
    overflow: "hidden",
    backgroundColor: "transparent",
  },
  scanLine: {
    position: "absolute",
    top: SCAN_LINE_INSET,
    left: spacing.md,
    right: spacing.md,
    height: SCAN_LINE_HEIGHT,
    borderRadius: radius.pill,
    backgroundColor: colors.primary,
    zIndex: 2,
    elevation: 2,
  },
  scanSuccess: {
    ...StyleSheet.absoluteFillObject,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.cameraScrim,
  },
  corner: {
    position: "absolute",
    width: spacing.xl,
    height: spacing.xl,
    borderColor: colors.primary,
    zIndex: 1,
  },
  cornerTopLeft: {
    top: spacing.xs,
    left: spacing.xs,
    borderTopWidth: spacing.xxs,
    borderLeftWidth: spacing.xxs,
    borderTopLeftRadius: radius.lg,
  },
  cornerTopRight: {
    top: spacing.xs,
    right: spacing.xs,
    borderTopWidth: spacing.xxs,
    borderRightWidth: spacing.xxs,
    borderTopRightRadius: radius.lg,
  },
  cornerBottomLeft: {
    bottom: spacing.xs,
    left: spacing.xs,
    borderBottomWidth: spacing.xxs,
    borderLeftWidth: spacing.xxs,
    borderBottomLeftRadius: radius.lg,
  },
  cornerBottomRight: {
    right: spacing.xs,
    bottom: spacing.xs,
    borderRightWidth: spacing.xxs,
    borderBottomWidth: spacing.xxs,
    borderBottomRightRadius: radius.lg,
  },
  bottomStack: {
    gap: spacing.sm,
  },
  cameraActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
  },
  cameraActionsStacked: {
    flexDirection: "column",
    alignItems: "stretch",
  },
  flashButton: {
    width: touchTarget.min,
    height: touchTarget.min,
    borderRadius: radius.pill,
    backgroundColor: colors.cameraControl,
    alignItems: "center",
    justifyContent: "center",
  },
  flashButtonActive: {
    backgroundColor: colors.primarySoft,
  },
  flashButtonActivePressed: {
    backgroundColor: colors.primarySoftPressed,
  },
  flashButtonPressed: {
    backgroundColor: colors.cameraControlPressed,
  },
  manualAction: {
    flex: 1,
    minHeight: touchTarget.min,
    borderRadius: radius.pill,
    backgroundColor: colors.cameraControl,
    paddingHorizontal: spacing.md,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.xs,
  },
  manualActionStacked: {
    flex: 0,
    width: "100%",
    paddingVertical: spacing.xs,
  },
  manualActionPressed: {
    backgroundColor: colors.cameraControlPressed,
  },
  manualActionLabel: {
    flexShrink: 1,
    textAlign: "center",
    fontSize: typography.bodySmall.fontSize,
    lineHeight: typography.bodySmall.lineHeight,
    fontFamily: typography.bodyStrong.fontFamily,
    color: colors.surface,
    textShadowColor: colors.cameraControl,
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  loadingStrip: {
    minHeight: touchTarget.min,
    borderRadius: radius.xxl,
    backgroundColor: colors.surface,
    paddingHorizontal: spacing.md,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
  },
  loadingText: {
    fontSize: typography.bodySmall.fontSize,
    lineHeight: typography.bodySmall.lineHeight,
    fontFamily: typography.bodyStrong.fontFamily,
    color: colors.text,
  },
  errorStrip: {
    borderRadius: radius.xxl,
    backgroundColor: colors.dangerSoft,
    padding: spacing.md,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    minHeight: touchTarget.min,
  },
  errorText: {
    flex: 1,
    fontSize: typography.bodySmall.fontSize,
    lineHeight: typography.bodySmall.lineHeight,
    fontFamily: typography.bodyStrong.fontFamily,
    color: colors.danger,
  },
  centerStage: {
    flex: 1,
    justifyContent: "center",
    alignItems: "stretch",
  },
  centerCard: {
    alignSelf: "stretch",
    borderRadius: radius.xxl,
    backgroundColor: colors.surface,
    padding: spacing.lg,
    gap: spacing.md,
    alignItems: "stretch",
  },
  centerTitle: {
    fontSize: typography.heading.fontSize,
    lineHeight: typography.heading.lineHeight,
    fontFamily: typography.heading.fontFamily,
    color: colors.text,
    textAlign: "center",
  },
  centerBubble: {
    alignSelf: "stretch",
  },
  sheetFooter: {
    gap: spacing.sm,
  },
  ctaHint: {
    fontSize: typography.bodySmall.fontSize,
    lineHeight: typography.bodySmall.lineHeight,
    fontFamily: typography.bodySmall.fontFamily,
    color: colors.mutedText,
    textAlign: "center",
  },
  productRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.md,
    borderRadius: radius.xxl,
    backgroundColor: colors.mutedSurface,
    padding: spacing.md,
  },
  productImage: {
    width: spacing.xxxl,
    height: spacing.xxxl,
    borderRadius: radius.lg,
    backgroundColor: colors.surface,
  },
  productImageFallback: {
    width: spacing.xxxl,
    height: spacing.xxxl,
    borderRadius: radius.lg,
    backgroundColor: colors.primarySoft,
    alignItems: "center",
    justifyContent: "center",
  },
  productCopy: {
    flex: 1,
    gap: spacing.xxs,
  },
  productEyebrow: {
    fontSize: typography.caption.fontSize,
    lineHeight: typography.caption.lineHeight,
    fontFamily: typography.label.fontFamily,
    color: colors.primary,
  },
  productName: {
    fontSize: typography.body.fontSize,
    lineHeight: typography.body.lineHeight,
    fontFamily: typography.title.fontFamily,
    color: colors.text,
  },
  productBarcode: {
    fontSize: typography.label.fontSize,
    lineHeight: typography.label.lineHeight,
    fontFamily: typography.label.fontFamily,
    color: colors.subtext,
  },
  manualNameCard: {
    borderRadius: radius.xxl,
    backgroundColor: colors.mutedSurface,
    padding: spacing.md,
    gap: spacing.sm,
  },
  manualNameLabel: {
    fontSize: typography.body.fontSize,
    lineHeight: typography.body.lineHeight,
    fontFamily: typography.title.fontFamily,
    color: colors.text,
  },
  manualNameInput: {
    minHeight: touchTarget.cta,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    paddingHorizontal: spacing.md,
    color: colors.text,
    fontSize: typography.body.fontSize,
    fontFamily: typography.bodyStrong.fontFamily,
  },
  manualNameInputError: {
    borderColor: colors.danger,
  },
  manualNameHint: {
    fontSize: typography.label.fontSize,
    lineHeight: typography.label.lineHeight,
    fontFamily: typography.label.fontFamily,
    color: colors.subtext,
  },
  quickAdjustmentCard: {
    borderRadius: radius.xxl,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.mutedSurface,
    padding: spacing.md,
    gap: spacing.md,
  },
  quickAdjustmentHeader: {
    gap: spacing.xxs,
  },
  quickLocationBlock: {
    gap: spacing.xs,
  },
  expiryCard: {
    borderRadius: radius.xxl,
    borderWidth: 1,
    borderColor: colors.border,
    padding: spacing.md,
    gap: spacing.xxs,
  },
  expiryLabel: {
    fontSize: typography.label.fontSize,
    lineHeight: typography.label.lineHeight,
    fontFamily: typography.label.fontFamily,
    color: colors.subtext,
  },
  expiryValue: {
    fontSize: typography.title.fontSize,
    lineHeight: typography.title.lineHeight,
    fontFamily: typography.title.fontFamily,
    color: colors.text,
  },
  manualExpiryCard: {
    borderRadius: radius.xxl,
    backgroundColor: colors.mutedSurface,
    padding: spacing.md,
    gap: spacing.md,
  },
  manualExpiryLabel: {
    fontSize: typography.body.fontSize,
    lineHeight: typography.body.lineHeight,
    fontFamily: typography.title.fontFamily,
    color: colors.text,
  },
  manualExpiryHint: {
    fontSize: typography.caption.fontSize,
    lineHeight: typography.caption.lineHeight,
    fontFamily: typography.label.fontFamily,
    color: colors.subtext,
    textAlign: "center",
  },
  pillRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.xs,
  },
  inlinePickerWrap: {
    alignItems: "center",
    width: "100%",
    borderRadius: radius.lg,
    backgroundColor: colors.surface,
    overflow: "hidden",
  },
  inlinePicker: {
    alignSelf: "center",
    width: "100%",
  },
  androidDateTrigger: {
    minHeight: touchTarget.cta,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
    justifyContent: "space-between",
    gap: spacing.xs,
  },
  androidDateTriggerPressed: {
    backgroundColor: colors.surfacePressed,
  },
  androidDateValue: {
    fontSize: typography.body.fontSize,
    lineHeight: typography.body.lineHeight,
    fontFamily: typography.bodyStrong.fontFamily,
    color: colors.text,
  },
  androidDatePlaceholder: {
    fontSize: typography.body.fontSize,
    lineHeight: typography.body.lineHeight,
    fontFamily: typography.body.fontFamily,
    color: colors.mutedText,
  },
  androidDateAction: {
    fontSize: typography.label.fontSize,
    lineHeight: typography.label.lineHeight,
    color: colors.primary,
    fontFamily: typography.label.fontFamily,
  },
  sheetFootnote: {
    fontSize: typography.label.fontSize,
    lineHeight: typography.label.lineHeight,
    fontFamily: typography.label.fontFamily,
    color: colors.subtext,
  },
  moderationErrorCard: {
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.danger,
    backgroundColor: colors.dangerSoft,
    padding: spacing.md,
  },
  moderationErrorText: {
    fontSize: typography.label.fontSize,
    lineHeight: typography.label.lineHeight,
    fontFamily: typography.bodyStrong.fontFamily,
    color: colors.danger,
  },
  quickSavedCard: {
    borderRadius: radius.xxl,
    borderWidth: 1,
    borderColor: colors.primary,
    backgroundColor: colors.primarySoft,
    padding: spacing.md,
  },
  quickSummaryRow: {
    minHeight: touchTarget.min,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.md,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
  },
  quickSummaryLabel: {
    flexShrink: 0,
    fontSize: typography.label.fontSize,
    lineHeight: typography.label.lineHeight,
    fontFamily: typography.label.fontFamily,
    color: colors.subtext,
  },
  quickSummaryValue: {
    flex: 1,
    textAlign: "right",
    fontSize: typography.body.fontSize,
    lineHeight: typography.body.lineHeight,
    fontFamily: typography.bodyStrong.fontFamily,
    color: colors.text,
  },
});
